name: presenceapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  image_picker: 0.8.6+1
  path_provider: 2.0.12
  convex_bottom_bar: 3.2.0
  intl: ^0.17.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  flutter: 
    sdk: flutter
  syncfusion_flutter_datepicker: ^20.4.49

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

dev_dependencies: 
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

